# Generated by Django 5.0.3 on 2024-03-28 03:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("donar", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DonarUserModel",
            new_name="UserModel",
        ),
    ]
