# Generated by Django 5.0.3 on 2024-03-28 03:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("donar", "0002_rename_donarusermodel_usermodel"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserModel",
            new_name="DonarUserModel",
        ),
        migrations.AlterModelTable(
            name="donarusermodel",
            table="donar_user",
        ),
    ]
