# Generated by Django 5.0.3 on 2024-03-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donar", "0003_rename_usermodel_donarusermodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donarusermodel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
