# Generated by Django 5.0.3 on 2024-03-28 03:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("donar", "0004_alter_donarusermodel_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donarusermodel",
            options={
                "verbose_name": "Donar User",
                "verbose_name_plural": "Donar Users",
            },
        ),
    ]
