# Generated by Django 5.0.4 on 2024-05-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donar", "0005_addressmodel_city_addressmodel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="addressmodel",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
