# Generated by Django 5.0.3 on 2024-03-29 01:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("donar", "0005_alter_donarusermodel_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DonarUserModel",
            new_name="UserModel",
        ),
    ]
