# Generated by Django 5.0.3 on 2024-03-30 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0006_rename_donarusermodel_usermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel',
            new_name='UserDetailModel',
        ),
        migrations.AlterModelOptions(
            name='userdetailmodel',
            options={'verbose_name': 'Donar User Detail', 'verbose_name_plural': 'Donar Users Detail'},
        ),
        migrations.AlterModelTable(
            name='userdetailmodel',
            table='donar_user_detail',
        ),
    ]
