# Generated by Django 5.0.4 on 2024-05-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donar", "0007_remove_userdetailmodel_address_userdetailmodel_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="addressmodel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
