# Generated by Django 5.0.3 on 2024-03-30 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0007_rename_usermodel_userdetailmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetailmodel',
            options={'verbose_name': 'User Detail', 'verbose_name_plural': 'Users Detail'},
        ),
        migrations.RenameField(
            model_name='userdetailmodel',
            old_name='phone',
            new_name='mobile',
        ),
    ]
