# Generated by Django 5.0.4 on 2024-06-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donar", "0008_addressmodel_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="addressmodel",
            name="mobile",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="addressmodel",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
