# Generated by Django 5.0.3 on 2024-03-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0008_alter_userdetailmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailmodel',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
