# Generated by Django 5.0.4 on 2024-06-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donar", "0009_addressmodel_mobile_addressmodel_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addressmodel",
            name="mobile",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="addressmodel",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
