# Generated by Django 5.0.4 on 2024-04-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citymodel',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='statemodel',
            options={'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
        migrations.AlterModelTable(
            name='citymodel',
            table='City',
        ),
        migrations.AlterModelTable(
            name='statemodel',
            table='State',
        ),
    ]
