# Generated by Django 5.0.4 on 2024-05-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_orderaddressmodel_ordermodel_orderimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderimage',
            name='order',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='images',
            field=models.ManyToManyField(to='common.orderimage'),
        ),
        migrations.AlterField(
            model_name='orderimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
