# Generated by Django 5.0.4 on 2024-05-23 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_remove_orderimage_order_ordermodel_images_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordermodel",
            name="images",
        ),
    ]
