# Generated by Django 5.0.4 on 2024-06-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0009_bannermodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordermodel",
            name="donar",
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="order_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ongoing", "Ongoing"),
                    ("booked", "Booked"),
                    ("accept", "Accepted"),
                    ("complete", "Completed"),
                    ("cancel", "Cancelled"),
                ],
                max_length=50,
            ),
        ),
    ]
