# Generated by Django 5.0.4 on 2024-06-01 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0010_remove_ordermodel_donar_and_more"),
        ("ngo", "0010_rename_accept_type_ngodetailmodel_accept_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="ngo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_ngo",
                to="ngo.ngodetailmodel",
            ),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("ongoing", "Ongoing"),
                    ("booked", "Booked"),
                    ("accept", "Accepted"),
                    ("complete", "Completed"),
                    ("cancel", "Cancelled"),
                ],
                default="ongoing",
                max_length=50,
            ),
        ),
    ]
