# Generated by Django 5.0.4 on 2024-06-01 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0011_alter_ordermodel_ngo_alter_ordermodel_order_status"),
        ("donar", "0008_addressmodel_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="donar_address",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="donar.addressmodel",
            ),
            preserve_default=False,
        ),
    ]
