# Generated by Django 5.0.4 on 2024-06-01 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0013_ordermodel_donar"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderAddressModel",
        ),
    ]
