# Generated by Django 5.0.4 on 2024-06-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0014_delete_orderaddressmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderimage",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
