# Generated by Django 5.0.4 on 2024-06-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0015_alter_orderimage_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderimage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
