# Generated by Django 5.0.4 on 2024-06-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0016_alter_orderimage_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymodel",
            name="img",
            field=models.ImageField(default=1, upload_to="", verbose_name=0),
            preserve_default=False,
        ),
    ]
