# Generated by Django 5.0.4 on 2024-05-11 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_categorymodel'),
        ('ngo', '0003_alter_ngodetailmodel_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngodetailmodel',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='common.citymodel'),
        ),
    ]
