# Generated by Django 5.0.4 on 2024-05-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0004_ngodetailmodel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngodetailmodel',
            name='ngo_owner_ame',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
