# Generated by Django 5.0.4 on 2024-05-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0006_ngodetailmodel_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngodetailmodel',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ngodetailmodel',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
