# Generated by Django 5.0.4 on 2024-05-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ngo", "0007_ngodetailmodel_latitude_ngodetailmodel_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="ngodetailmodel",
            name="registration_step",
            field=models.IntegerField(default=1),
        ),
    ]
